version: "3.8"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  worker-dashboard:
    image: raghav1205/redis-worker:latest
    container_name: redis-worker
    ports:
      - "3000:3000"
   
   

volumes:
  redis_data:
    driver: local
